<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php echo $this->user->lang('Clientexec Installer') ?></title>
    <link rel="Shortcut Icon" href="favicon.ico" />
    <link href='//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Quattrocento+Sans:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="templates/admin/style/install.css" />
    <script type="text/javascript">
        var gHash = "<?php echo $this->gHash; ?>";
    </script>
    <script type="text/javascript" src="library/utilities/min/index.php?g=installer"></script>
</head>

<body>
<div class="install-header"><?php echo $this->user->lang('Clientexec Installer') ?></div>

<center>
<div id="main" style="width:80%;min-width:900px">

<div class="well">
    <form action="index.php?fuse=admin&amp;action=updateconfig&controller=installer" method="POST">
        <input type="hidden" name="install" value="<?php echo $this->install; ?>" />
        <input type="hidden" name="uninstall" value="<?php echo $this->uninstall; ?>" />
        <div style="padding:30px 0">
            <?php echo $this->user->lang('Please fill out the following MySQL connection settings') ?>:
        </div>

        <table border=0 cellpadding="5" cellspacing="1" align="center">
            <tr>
                <td align="right" valign=top><b><?php echo $this->user->lang('MySQL server name') ?>:</b></td>
                <td><input type=text name="dbserver" value="localhost"><br />
                <font size=1 class="submeta"><?php echo $this->user->lang('This is nearly always localhost, so if you don\'t know use localhost') ?>.</font></td>
            </tr>
            <tr>
                <td align="right" valign=top><b><?php echo $this->user->lang('MySQL username') ?>:</b></td>
                <td><input type=text name="dbuser" value=""><br />
                <font size=1 class="submeta"><?php echo $this->user->lang('Fill in the username you need to connect to your MySQL database') ?></font></td>
            </tr>
            <tr>
                <td align="right" valign=top><b><?php echo $this->user->lang('MySQL password') ?>:</b></td>
                <td><input type=password name="dbpassword" value=""><br />
                <font size=1 class="submeta"><?php echo $this->user->lang('Fill in the password you need to connect to your MySQL database') ?></font></td>
            </tr>
                <tr>
                <td align="right" valign=top><b><?php echo $this->user->lang('MySQL Database name') ?>:</b></td>
                <td style="width:400px"><input type=text name="dbname" value="<?php echo strtolower($this->gSoftwareName); ?>"><br />
                  <font size=1 class="submeta">
                    <?php echo $this->user->lang('Fill in the name of the database you want to use to let %s store its data in', $this->gSoftwareName) ?>.<br>
                    <b><i>
                      <?php echo $this->user->lang('Warning: Make sure it\'s empty or at least doesn\'t contain important info, it is very likely that it will be destroyed.  If this database does not exist, the installer will try to create it') ?>.
                    </i></b>
                  </font>
                </td>
            </tr>
        </table>
        <br>
        <input type=submit class="btn" value="<?php echo $this->user->lang('Continue Installing') ?>" onclick="submitonce(this.form); this.form.submit(); return false;" /><br><br>
    </form>
</div>

        </div>
</center>
</body>
</html>
