<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php echo $this->user->lang('Clientexec Installer') ?></title>
    <link rel="Shortcut Icon" href="favicon.ico" />
    <link href='//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Quattrocento+Sans:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="templates/admin/style/install.css" />
    <script type="text/javascript">
        var gHash = "<?php echo $this->gHash; ?>";
    </script>
    <script type="text/javascript" src="library/utilities/min/index.php?g=installer"></script>
</head>

<body>
<div class="install-header"><?php echo $this->user->lang("Clientexec Installer");?></div>

<center>
<div id="main" style="width:80%;min-width:900px">

<div class="well">
    <form action="index.php?fuse=admin&amp;action=createsuperadmin&controller=installer" method="POST">
        <div style="padding:10px 0">
            <?php echo $this->user->lang('You must now set up your administrator account on your %s installation', $this->gSoftwareName) ?>.<br><br>

        </div>
        <table border=0 cellspacing=0 cellpadding=3 align="center" style="width:500px">
            <tr>
                <td align="right" class="install-label" valign=top>
                  <b><?php echo $this->user->lang('Your email address') ?>:</b>
                </td>
                <td>
                  <input type=text name="email" value=""><br />
                  <font size=1 class="submeta"><?php echo $this->user->lang('You will use this Email account to login as the primary administrator') ?>.</font>
                </td>
            </tr>
            <tr>
                <td align="right" class="install-label" valign=top><b><?php echo $this->user->lang('Password') ?>:</b></td>
                <td><input type=password name="password1"><br />
                <font size=1 class="submeta"><?php echo $this->user->lang('Fill in your preferred password here') ?>.</font></td>
            </tr>
            <tr>
                <td align="right" class="install-label" valign=top><b><?php echo $this->user->lang('Password Verification') ?>:</b></td>
                <td><input type=password name="password2"></td>
            </tr>
        </table>

        <hr>

        <div style="padding:10px 0">
            <?php echo $this->user->lang('Please also fill in the following information') ?>:
        </div>

        <table border=0 cellspacing=0 cellpadding=3 align="center" style="width:500px">
            <tr>
                <td align="right" class="install-label" valign="top"><b><?php echo $this->user->lang('Company Name') ?>:</b></td>
                <td><input type="text" name="company_name"><br />
            </tr>
            <tr>
                <td align="right" class="install-label" valign="top"><b><?php echo $this->user->lang('Company URL') ?>:</b></td>
                <td><input type="text" name="company_url" value="<?php echo $this->company_url ?>"><br />
            </tr>
            <tr>
                <td colspan="2" align="right" class="install-label" valign="top"><input type="checkbox" name="notify_additional" checked="checked"> <b><div style="padding-top: 3px; float: right">Send me information regarding domain and payment gateways</div></b>
                <br />
                </td>
            </tr>
        </table>

        <input type=submit class="btn" value="<?php echo $this->user->lang('Continue to Last Step') ?>" style="margin-top:10px" onclick="submitonce(this.form); this.form.submit(); return false;" />
    </form>
</div>

        </div>
</center>
</body>
</html>
