<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php echo $this->user->lang('Clientexec Installer') ?></title>
    <link rel="Shortcut Icon" href="favicon.ico" />
    <link href='//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Quattrocento+Sans:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="templates/admin/style/install.css" />
    <script type="text/javascript">
        var gHash = "<?php echo $this->gHash; ?>";
    </script>
    <script type="text/javascript" src="library/utilities/min/index.php?g=installer"></script>
</head>
<body>
<div class="install-header"><?php echo $this->user->lang("Clientexec Installer");?></div>

<center>
<div id="main" style="width:80%;min-width:900px">

<div class="well">
    <table border=0 cellspacing=1 cellpadding=4 width=100%>
        <tr>
            <td align="center"><br>
            <h1><?php echo $this->user->lang('Thank you for choosing %s', $this->gSoftwareName) ?></h1><br/>
            <?php echo $this->user->lang('The installation process is now complete, <b><a href="%s/index.php?fuse=home&view=login">Login Now</a></b>', $this->softwareURL) ?>.<br /><br>
            <?php echo $this->user->lang('Join us in our <a href="http://slack.clientexec.rocks" target="_blank">community slack room</a> for all the latest news as well as community based support') ?>.<br /><br />
            </td>
        </tr>
    </table>
</div>

        </div>
</center>
</body>
</html>
