<html>
<table width="98%" cellpadding="0" cellspacing="0" border="0" align="center">
    <tr>
        <td>
            <table width='100%' cellpadding='2' cellspacing='2' border='0'>
                <thead>
                    <tr>
                        <td>
                            <span class="announcement_title"><?php echo $this->subject;?></span>
                            <br>
                            <span class="announcement_date"><?php echo $this->date;?></span>
                            <br><br>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="announcement_post">
                            <?php echo $this->unescape($this->body) ?>
                        </td>
                    </tr>
                </tbody>
            </table>
        </td>
    </tr>
</table>
</body>
</html>
