<div class="ce-container">

    <div class="alert resetpwd-description"><?php echo $this->user->lang("Reset your password by entering your registered Email address below. You will receive an Email shortly with instructions.");?></div>

    <table cellspacing="0">
        <tr>
            <td colspan="2">
                <label><?php echo $this->user->lang("Email");?></label>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="text" class="customerEmail" data-required="true" data-type="email" name="customerEmail" value="">
            </td>
        </tr>
    </table>
</div>