<div class="alert ce-alert ce-alert-info">
    <?php echo $this->user->lang('Requesting cancellation for'); ?>: <?php echo $this->packageName; ?>
</div>

<form id="cancel-form" action="index.php?fuse=clients&controller=products&action=requestcancellation" method="POST">
    <input type="hidden" name="id" value="<?php echo $this->packageId; ?>" />

    <?php echo $this->user->lang('Please describe your reason for this cancellation request'); ?>:<br/>
    <textarea data-required="true" name="reason" rows='10' style="width: 95%"></textarea>

    Cancellation Type: <br/>
    <select name="type" id="type">
        <option value="<?php echo PACKAGE_CANCELLATION_TYPE_IMMEDIATE; ?>"><?php echo $this->user->lang('Immediate'); ?></option>
        <?php if ($this->paidInvoicesCount > 0) { ?>
        <option value="<?php echo PACKAGE_CANCELLATION_TYPE_END_BILLING; ?>"><?php echo $this->user->lang('End of Billing Period'); ?> (<?php echo $this->endOfBillingPeriod; ?>)</option>
        <?php } ?>
    </select>

    <div class="form-actions">
        <input id="submit-button" type="submit" value="<?php echo $this->user->lang('Submit'); ?>" class="btn btn-danger" />
        <input id="cancel-button" type="button" value="<?php echo $this->user->lang('Cancel'); ?>" class="btn" />
    </div>
</div>