<div class="alert alert-info ce-page-header">
  <div class="alert-header"><?php echo $this->user->lang("Customer Groups"); ?></div>
  <p class="alert-content"><?php echo $this->user->lang("Create custom groups for easy access and for identification purposes");?></p>
</div>

<span class="grid-meta" id="group-grid-metadata"></span>
<div id="gridheader" class="blue-box">
    <table class="automation">
        <tbody>
            <tr>
                <td><a id="addGroupButton" class="rich-button white"><span class="buttontext"><?php echo $this->user->lang("Add Customer Group");?></span></a></td>
            </tr>
        </tbody>
    </table>
</div>

<div id="group-grid"></div>
<div style="clear:both;" />