<script data-cfasync="false" type="text/javascript">
    var eventlist = eventlist || {};
    eventlist.startDateValue = '<?php echo $this->startDateValue; ?>';
    eventlist.endDateValue = '<?php echo $this->endDateValue; ?>';
    eventlist.eventType = 'all';
</script>

<div class="alert alert-info ce-page-header">
  <div class="alert-header"><?php echo $this->user->lang('Event List');?></div>
  <p class="alert-content"><?php echo $this->user->lang('View recent activity of your Clientexec Installation.');?></p>
</div>

<div class="alert ce-alert-info" style="margin-bottom:0;">
    <div style="width: 165px;float: left;"><span style="position:relative;top:2px;"><?php echo $this->user->lang('Start Date'); ?>:</span>&nbsp;
        <input class='datepicker' type='text' name="startdate" id="startdate" value='<?php echo $this->startDateValue; ?>' />
    </div>
    <div style="width: 165px;float: left;"><span style="position:relative;top:2px;"><?php echo $this->user->lang('End Date'); ?>:</span>&nbsp;
        <input class='datepicker' type='text' name="enddate" id="enddate" value='<?php echo $this->endDateValue; ?>' />
    </div>
    <div>
        <select name="eventtype" style="width:230px;" id="eventtype">
            <option value="all"><?php echo $this->user->lang('All events'); ?></option>
            <?php if ( isset($this->profileAndPackagesEvents) ) { ?>
            <option value="profileandpackages"><?php echo $this->user->lang('Profile and Packages events'); ?></option>
            <option value="domainrenewals"><?php echo $this->user->lang('Domain Renewal Notifications'); ?></option>
            <?php } ?>

            <?php if ( isset($this->profileEvents) ) { ?>
            <option value="profileandpackages"><?php echo $this->user->lang('Profile events'); ?></option>
            <?php } ?>

            <?php if ( isset($this->billingEvents) ) { ?>
            <option value="billing"><?php echo $this->user->lang('Billing events'); ?></option>
            <?php } ?>

            <?php if ( isset($this->supportEvents) ) { ?>
            <option value="support"><?php echo $this->user->lang('Support Tickets events'); ?></option>
            <?php } ?>

            <option value="note"><?php echo $this->user->lang('Client/Group Note'); ?></option>
            <option value="emails"><?php echo $this->user->lang('Email events'); ?></option>
            <option value="errors"><?php echo $this->user->lang('Process Errors'); ?></option>
            <option value="login"><?php echo $this->user->lang('Login Attempts'); ?></option>
        </select>

        <a class="rich-button white" id="btnSubmitSearch" style="margin-left: 20px;height: 19px;padding-top: 7px;"><span class="buttontext"><?php echo $this->user->lang("Search"); ?></span></a>
    </div>
</div>

<br/>
<span class="grid-meta" id="event-grid-metadata" style="clear:both;"></span>
<div class="blue-box">
    <table class="automation">
        <tbody>
            <tr>
                <td><?php echo $this->user->lang('Event List'); ?></td>
                <td align="left" style="width:60px">
                    <select id='events-grid-filter' class="change-grid-showrecords" style='width:60px;'><option value='5'>5</option><option value='10'>10</option><option value='25'>25</option><option value='50'>50</option><option value='150'>150</option><option value='300'>300</option></select>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div id="event-grid"></div>
