<div class="alert alert-info ce-page-header">
  <div class="alert-header"><?php echo $this->user->lang("Security Settings - Domain Encryption");?></div>
  <p class="alert-content"><?php echo $this->user->lang("Manage hosting password encryption");?></p>
</div>

<h3><?php echo $this->user->lang("Encrypt Domain Passwords");?></h3>
<?php echo $this->user->lang("Encrypt/Decrypt your customer's domain passwords");?>.
<br/>
<font class=red>
    <?php echo $this->user->lang("Performing this action could take some time, please be patient");?>
</font>
<br>
<br>
<b>
    <font color=<?php echo $this->COLOR;?>>
        <?php echo $this->unescape($this->STATUS);?>
    </font>
</b>
<br>
<br>
<form name="encryptdomainpasswords" method="post" action="index.php?fuse=admin&action=encryptdomainpasswords&settings=security&controller=settings">
    <table>
        <tr>
            <td colspan=2>
                <button <?php echo $this->DISABLED;?> class="btn"><?php echo $this->BUTTON_NAME;?></button>
            </td>
        </tr>
    </table>
</form>


<?php if ($this->MESSAGE != "") { ?>
    <br>
    <font color=red>
    <center>
        <b>
            <?php echo $this->MESSAGE;?>
        </b>
    </center>
    </font>
<?php } ?>