<?php echo $this->partial('signuppublic/cartheader.phtml', array('tempInformation'=>$this->tempInformation,'user'=>$this->user,'step'=> 3, 'summary'=>$this->summary));?>
<div class="ce-box">
    <div class="ce-box-inner">
        <form action="index.php?fuse=admin&controller=signup&action=phoneverificationcheck" method="post">
          <h1><?php echo $this->user->lang("Telephone Verification");?></h1>
          <p class="sub_header">
            <?php echo $this->user->lang('In order to help prevent fraudulent orders we require new customers to verify their phone number');?>.
          </p>
          <?php if (!$this->isCalled): ?>
            <p><strong><?php echo $this->user->lang("Please wait, you will be called at")." ". @$this->phoneNumber ." ".$this->user->lang("within 30 seconds.");?> </strong></p>
          <?php else: ?>
            <p><strong><?php echo $this->user->lang("According to our records we have previously called you. If you did not receive a call within 30 seconds please click the back button and verify that your phone number is in the correct format. Please be aware that a new code will be issued");?> </strong></p>
          <?php endif ?>

          <div class="customfields-wrapper">
            <label class="customfield_label"><?php echo $this->user->lang('Please enter the code given to you by the robotic system:') ?></label>
            <input type="text" name="code">
          </div>

          <div class="form-actions">
            <input type="submit" class="pull-right btn btn-large" value="<?php echo $this->user->lang('Continue') ?>">
          </div>
        </form>
    </div>
</div>

