<div class="invalid-license">
<h1><?php echo $this->user->lang("Invalid license for domain");?><br>
<span class="invalid-license-domain"><i><?php echo $_SERVER['HTTP_HOST'];?></i></span></h1>

<div class="invalid-contact-info">
If you obtained your license from your hosting company please contact them.<br>
Otherwise email us at <a href="mailto://support@clientexec.com">support@clientexec.com</a>
</div>

<a href="http://www.clientexec.com?source=poweredby" target="_new"><img class="brand-logo" src="templates/common/img/logo_text.png"></a>

</div>