<input type="hidden" id="paystack_transaction_id" name="paystack_plugincustomfields[paystack_transaction_id]" value="">

<script src="https://js.paystack.co/v1/inline.js"></script>
<?php if ($this->from == 'signup') { ?>
<a style="margin-left:0px;cursor:pointer;" class="pull-right btn btn-large customButton paystackButton <?php if(@$this->termsConditions) { ?>disabled<?php } ?>" id="customButton"></a>
<?php } else if ($this->from == 'invoice') { ?>
<button style="margin-left:0px;cursor:pointer;" class="pull-right btn btn-large customButton paystackButton" id="customButton"><?php echo $this->user->lang('Pay Invoice'); ?></button>
<?php } ?>

<script>
    function paystackOpenHandler(){
        var handler = PaystackPop.setup({
            key: '<?php echo $this->publicKey; ?>',

            <?php if ($this->from == 'invoice') { ?>
                email: '<?php echo $this->user->getEmail(); ?>',
                amount: '<?php echo $this->amount; ?>',
            <?php } else if ($this->from == 'signup')  { ?>
                email: document.getElementById("CT_4").value+'<?php echo @$this->user->getEmail(); ?>',
                amount: (document.getElementById("totalPay_raw").value * 100),
            <?php } ?>

            callback: function(response) {
                document.getElementById('paystack_transaction_id').value = response.trxref;

                <?php if ($this->from == 'invoice' || $this->from == 'signup') { ?>
                    $('#submitButton').click();
                <?php } ?>
            }
        });
        handler.openIframe();
    }

    $('.paystackButton').on('click', function(e) {
        e.preventDefault();

        <?php if ($this->from == 'signup') { ?>
            if ($('.paystackButton').hasClass('disabled')) {
                return;
            }
        <?php } ?>
        paystackOpenHandler();
    });
</script>