<table width="{PHPINFO_BARWIDTH}%">
<tr>
 <td width="100%">
  <table width="100%" height="14" cellspacing="0" cellpadding="0" border="0" background="../../plugins/snapins/phpsysinfo/images/{PHPINFO_BARPREFIX}-back.gif">
   <tr>               
    <td width="3" align="left"><img src="../plugins/snapins/phpsysinfo/images/{PHPINFO_BARPREFIX}-start.gif"></td>
    
    <!-- BEGIN DYNAMIC BLOCK: bar_option1 -->
    <td width="{PHPINFO_BARVALUE}%" background="../../plugins/snapins/phpsysinfo/images/{PHPINFO_BARPREFIX}-active.gif"><img src="../plugins/snapins/phpsysinfo/images/zero.gif" width="1" height="1"></td>
    <!-- END DYNAMIC BLOCK: bar_option1 -->
    
    <!-- BEGIN DYNAMIC BLOCK: bar_option2 -->
    <td width="4"><img src="../plugins/snapins/phpsysinfo/images/{PHPINFO_BARPREFIX}-divider.gif"></td>
    <!-- END DYNAMIC BLOCK: bar_option2 -->
    
    <!-- BEGIN DYNAMIC BLOCK: bar_option3 -->
    <td width="{PHPINFO_BARLEFT}%"><img src="../plugins/snapins/phpsysinfo/images/zero.gif" width="1" height="1"></td>
    <!-- END DYNAMIC BLOCK: bar_option3 -->
    
    <!-- BEGIN DYNAMIC BLOCK: bar_option4 -->
    <td width="3" align="right"><img src="../plugins/snapins/phpsysinfo/images/{PHPINFO_BARPREFIX}-end.gif"></td>
    <!-- END DYNAMIC BLOCK: bar_option4 -->
    
    <!-- BEGIN DYNAMIC BLOCK: bar_option5 -->
    <td width="2" align="right"><img src="../plugins/snapins/phpsysinfo/images/{PHPINFO_BARPREFIX}-zeroend.gif"></td>
    <!-- END DYNAMIC BLOCK: bar_option5 -->
    
   </tr>
  </table>
  </td>
<td width="1" class="text">{PHPINFO_BARVALUE}</td>
</tr>
</table>
